# Generated by Django 5.1.4 on 2025-01-10 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeusMagnusMainPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azobeoj_title', models.CharField(blank=True, max_length=255, null=True)),
                ('azobeoj_status', models.CharField(blank=True, max_length=255, null=True)),
                ('azobeoj_description', models.TextField()),
                ('azobeoj_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('azobeoj_magnus_img', models.ImageField(upload_to='images/')),
                ('azobeoj_publish_date', models.DateTimeField(auto_now_add=True)),
                ('azobeoj_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-azobeoj_publish_date'],
            },
        ),
    ]
