# Generated by Django 5.1.4 on 2025-01-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azobeoj', '0003_remove_azobeojmainpost_azobeoj_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azobeojmainpost',
            old_name='azobeoj_status',
            new_name='azobeoj_title',
        ),
    ]
