# Generated by Django 5.1.4 on 2025-01-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azobeoj', '0004_rename_azobeoj_status_azobeojmainpost_azobeoj_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='azobeojmainpost',
            name='azobeoj_magnus_img_1',
            field=models.ImageField(default=1, upload_to='images_1/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='azobeojmainpost',
            name='azobeoj_magnus_img_2',
            field=models.ImageField(default=1, upload_to='images_2/'),
            preserve_default=False,
        ),
    ]
