# Generated by Django 5.1.4 on 2025-01-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azobeoj', '0005_azobeojmainpost_azobeoj_magnus_img_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azobeojmainpost',
            name='azobeoj_description_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
