# Generated by Django 5.1.4 on 2025-01-14 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azobeoj', '0006_azobeojmainpost_azobeoj_description_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LastAzobeojMainPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_title', models.CharField(blank=True, max_length=255, null=True)),
                ('last_description', models.TextField()),
                ('last_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('last_magnus_img', models.ImageField(upload_to='last_images/')),
                ('last_publish_date', models.DateTimeField(auto_now_add=True)),
                ('last_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_publish_date'],
            },
        ),
    ]
