# Generated by Django 5.1.4 on 2025-01-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azobeoj', '0007_lastazobeojmainpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_video', models.FileField(upload_to='contact_videos/')),
            ],
        ),
    ]
