# Generated by Django 5.1.4 on 2025-01-16 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azobeoj', '0008_contactvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AzobeojProjectsMainPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_title', models.CharField(blank=True, max_length=255, null=True)),
                ('projects_description', models.TextField()),
                ('projects_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('projects_magnus_img', models.ImageField(upload_to='project_images/')),
                ('projects_publish_date', models.DateTimeField(auto_now_add=True)),
                ('projects_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-projects_publish_date'],
            },
        ),
    ]
