# Generated by Django 5.2.7 on 2026-01-20 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azobeoj', '0009_azobeojprojectsmainpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsMainPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_title', models.CharField(blank=True, max_length=255, null=True)),
                ('team_description', models.TextField()),
                ('team_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('team_magnus_img', models.ImageField(upload_to='team_images/')),
                ('team_publish_date', models.DateTimeField(auto_now_add=True)),
                ('team_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-team_publish_date'],
            },
        ),
    ]
